- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
        name: "{{ tag_name }}"
        key_name: "{{ key_name }}"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: yes
        count: 1
        security_group: "{{ security_group }}"
        tags:
          Name: "{{ tag_name }}"
      register: ec2

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        timeout: 300

    - name: Add new instance to inventory
      ansible.builtin.add_host:
        name: nginx_server
        ansible_host: "{{ ec2.instances[0].public_ip_address }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/my-key.pem
