- name: Deploy Nginx Container
  hosts: nginx_server
  become: yes
  tasks:
    - name: Create directory for custom HTML
      file:
        path: /home/ec2-user/nginx-html
        state: directory
        owner: ec2-user

    - name: Copy custom index.html
      copy:
        src: files/index.html
        dest: /home/ec2-user/nginx-html/index.html
        owner: ec2-user

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /home/ec2-user/nginx-html:/usr/share/nginx/html:ro
